import Head from 'next/head';
import HeroComponent from '@/components/Home/Hero';
import ServicesComponents from '@/components/Home/Services';
import ContactUsComponent from '@/components/Home/ContactUs';
import TechStackComponent from '@/components/Home/TechStack';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HeroComponent />
      <ServicesComponents />
      <TechStackComponent />
      <ContactUsComponent />
    </>
  );
}
